//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_2051010137_VoDinhKhang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen_ThanhVien
    {
        public int MaThanhVien { get; set; }
        public int MaPQ { get; set; }
        public string GhiChu { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
        public virtual ThanhVien ThanhVien { get; set; }
    }
}
